### ISSUE TITLE
Boxin: GitHub profile link broken

### ISSUE THREAD

**Issue by whipermr5** [nus-oss/cs3281-website#125]
As per title, on ~~both student list and~~ resume page @boxin-yang

**Comment by damithc** [comment]
@boxin-yang FYI

**Comment by boxin-yang** [comment]
updated in my last PR. Thx for the notice :)

**Comment by whipermr5** [comment]
Update your [resume](https://github.com/nus-oss/cs3281-website/blob/f11bc692e36597ee2c5c9008c51dbd5b591c0ffe/students/AY1617S2/yangBoxin/YangBoxin-Resume.md) too :)

**Comment by boxin-yang** [comment]
oh wow! missed that
